config/routes.rb
CookieHunter::Application.routes.draw do
  devise_for :hunters

  root :to => "huntings#show"

  resource :hunting, only: :show
  resource :stockpile, only: [] do
    get :add
    get :steal
  end
  resource :bucket, only: [] do
    get :get
  end
  resource :bonuses, only: [] do
    get :buy
  end
  resource :cookies, only: [:show]

end

app/models/hunting.rb
class Hunting

  ATTRIBUTES = %i(hunter stockpile hunters steal_bucket active_bonuses all_bonuses)
  attr_reader *ATTRIBUTES

  def initialize(hunter)
    @hunter = hunter
    @stockpile = @hunter.stockpile
    all_hunters = Hunter.select(:id, :email).where(nil).to_a
    all_hunters.delete(hunter)
    @hunters = all_hunters.map{|hunter| { id: hunter.id, email: hunter.email, cookies: hunter.cookies}}
    @steal_bucket = StealBucket.instance
    @active_bonuses = @hunter.active_bonuses
    @all_bonuses = Bonuses::Bonus.all_bonuses_for(@stockpile)
  end

end

app/controllers/huntings_controller.rb
class HuntingsController < ApplicationController
  include DoubleRequestProtected

  before_filter :authenticate_hunter!
  after_filter :double_request_lock

  def show
    @hunting = Hunting.new(@hunter)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @hunting.to_json }
    end
  end

end

app/views/huntings/_bonuses_div.html.erb
<h3>Bonuses</h3>
<div class='active_bonuses'>
  <h4>Active Bonuses</h4>
  <% @hunting.active_bonuses.each do |bonus| %>
      <div class='active_bonus'>
        <p><%= "#{bonus[:name]}: #{bonus[:regeneration]} * #{bonus[:count]}" %></p>
      </div>
  <% end %>
</div>
<div class='available_bonuses'>
  <h4>Available bonuses</h4>
  <% @hunting.all_bonuses.each do |bonus| %>
      <div class='available_bonus'>
        <%= link_to "#{bonus[:name]} (#{bonus[:value]}): Price: #{bonus[:price]}",
                    buy_bonuses_path(type: bonus[:class]),
                    title: bonus[:description],
                    class: "btn btn-success btn-large",
                    id: "bonus_#{bonus[:class]}"
        %>
      </div>
  <% end %>
</div>

app/views/huntings/_cookies_div.html.erb
<h3>Cookies</h3>
<div class='info'>
  <p>Get <%= @hunting.stockpile.clicks %> cookies per click</p>
  <p>Regenerate <%= @hunting.stockpile.regeneration %> cookies per 10 sec</p>
  <p>Steal <%= @hunting.stockpile.steals %> cookies per click</p>
  <p>Stockpile saves <%= @hunting.stockpile.saves %> cookies forever</p>
</div>

<div class='cookies_link'>
  <%= link_to "Cookies: #{@hunting.hunter.cookies}", add_stockpile_path,
              class: 'btn btn-success btn-large', id: 'add_cookie_link' %>
</div>
<div class='steal_bucket_link'>
  <%= link_to "StealBucket: #{@hunting.steal_bucket.cookies}", get_bucket_path,
                 class: 'btn btn-success btn-large', id: 'get_steal_bucket_link' %>
</div>

app/views/huntings/_hunters_div.html.erb
<h3>Users</h3>
<p>Text</p>
<div>
  <ul class='hunter_list'>
    <% @hunting.hunters.each do |hunter| %>
        <li class='hunter <%= "hunter_#{hunter[:id]}" %>'>
          <%= link_to "#{hunter[:email]} (#{hunter[:cookies]})", steal_stockpile_path(hunter_id: hunter[:id]),
                      class: 'btn btn-success btn-large hunter_link',
                      id: "steal_from_hunter_#{hunter[:id]}",
                      data: { id: hunter[:id], email: hunter[:email] } %>
        </li>
    <% end %>
  </ul>
</div>

app/views/huntings/show.html.erb
<div class='row' id='hunting'>
  <div class='span4' id='cookies_div'>
    <%= render 'cookies_div' %>
  </div>

  <div class='span4' id='hunters_div'>
    <%= render 'hunters_div' %>
  </div>

  <div class='span4' id='bonuses_div'>
    <%= render 'bonuses_div' %>
  </div>

</div>

<script type='text/javascript'>
    $(function(){
        window.hunting = new window.Hunting($('#hunting_div'))
    })
</script>