config/routes.rb
CookieHunter::Application.routes.draw do
  devise_for :hunters

  root :to => "huntings#show"

  resource :hunting, only: :show
  resource :stockpile, only: [] do
    get :add
    get :steal
  end
  resource :bucket, only: [] do
    get :get
  end
  resource :bonuses, only: [] do
    get :buy
  end
  resource :cookies, only: [:show]

end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Cookie Hunter</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if current_hunter %>
              <li><%= link_to "Sign Out", destroy_hunter_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Sign In", new_hunter_session_path %></li>
              <li><%= link_to "Sign Up", new_hunter_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notices.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieHunter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/notices' %>

  <%= yield %>

</div>

</body>
</html>